language: node_js
node_js:
- stable
branches:
  only: master
script: yarn lint && yarn test
cache: yarn
notifications:
  slack:
    rooms:
      secure: hbCQTzJAKwC8sdFNREaf14PGa9ZBPCBMw6XVuVDJ5s6wkUiNOLZN7oT1frF/2tw01767gKxFwlDMxYz2WBFqC6hKNpGzfFnWqD1eBTSpFcPdEgrTIbQzDomX7atk2MgUIErsQIA1ArZ8a5QBPaX7PF9rsFOEgoKzmA0L9RgOj6Jw4j0D6xgyxwtD75XCDeAxIf1A971P5vougIGEe3V8u4G7bAZNbXHOExlIH9n+d6KWIBzGZjnPr5Me3UJ7HUJkPE1aNsSLqIplZ5YP3c6ODCKLq9csGRyEF5oIPcpXAUyHJISU/7r/7n0DKdhcoe5NJGipDGh/3S3LBJ5gz+pCu8Pb+IceT2z9yx3fS6acpkk3pqILUqQyJDWjifsQlm0OdfnaXxM2eXaCE8SkaFPGSMVHZSB/ZrouVh0XHUzkavpIXVEsb9lPOX6zA8cPiRivi3N5NFVVmqDBw16dQiRWRePs+2P5WW3meE5oD/It7NXI7xQXv8e3qNmtPvErO4ANBpSTgqUQbMIBInWsdXh4c6PXTRMtsH8Od4svHpEtK3UFaeRkKC1Aam26/w5p16kERl0PGlKPG86F42J0W97Jr9YoC8DLch88ENGoVyCo1aWR+JunEmVItIApVTIU7ww/gQ0Sf5EulNhS6QLvdsbQkbIvTDKuHsukfeDnl8FQNpg=
