import analyticsCalls from "./calls/analytics";
import announcementCalls from "./calls/announcement";
import commentCalls from "./calls/comment";
import departmentCalls from "./calls/department";
import eventCalls from "./calls/event";
import expenseCalls from "./calls/expense";
import feedbackCalls from "./calls/feedback";
import interestCalls from "./calls/interest";
import inviteCalls from "./calls/invite";
import organizationCalls from "./calls/organization";
import passwordCalls from "./calls/password";
import redemptionCalls from "./calls/redemption";
import rewardCalls from "./calls/reward";
import userCalls from "./calls/user";

export default object => {
  analyticsCalls(object);
  announcementCalls(object);
  commentCalls(object);
  departmentCalls(object);
  eventCalls(object);
  expenseCalls(object);
  feedbackCalls(object);
  interestCalls(object);
  inviteCalls(object);
  organizationCalls(object);
  passwordCalls(object);
  redemptionCalls(object);
  rewardCalls(object);
  userCalls(object);
  return object;
};
